"""empty message

Revision ID: 197cc33a2c8f
Revises: 4c96355cb8fa
Create Date: 2018-10-07 11:40:37.948536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197cc33a2c8f'
down_revision = '4c96355cb8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('common_post', sa.Column('readCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('common_post', 'readCount')
    # ### end Alembic commands ###
